### ISSUE TITLE
Is there a way to test if its working?

### ISSUE THREAD

**Issue by hybritect** [mayrs/der-bergdoktorbot-a-doctolib-doctors-appointment-telegram-notifier#1]
Hi, 
great script. I managed to run it on Visual Studio and it helped me get an appointment once. 
Now I have 15 instances of it scraping different doctors. Is there a way to test if it's working?

Thank you!

**Comment by mayrs** [comment]
Thanks @hybritect ! You can test it's working by setting [`MAX_DATETIME_IN_FUTURE`](https://github.com/mayrs/der-bergdoktorbot-a-doctolib-doctors-appointment-telegram-notifier?tab=readme-ov-file#max_datetime_in_future) to one day after a known date. Let's say you know from the Doctolib page that there's a free appointment on the `20th of July 2024` set `MAX_DATETIME_IN_FUTURE` to the `21st of July 2024` and run your script. It should now find the knowingly free appointment and alert you. Does that answer your question or did you mean something different?

Btw. shortly after I uploaded the script Doctolib introduced an 'in-app earlier appointment' toggle switch that does that for you. But might be, that relying on this script works around limitations/free tier limitations from the app? You never know :) .

**Comment by hybritect** [comment]
Ja, logisch :D

Thank you for the great work.
